# Use Ubuntu 22.04 as the base image
FROM ubuntu:22.04

# Prevent interactive prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update package list and install curl
RUN apt-get update && \
    apt-get install -y curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY apply_backup_to_docker.sh scripts/apply_backup_to_docker.sh
COPY setup_multiple_docker.sh scripts/setup_multiple_docker.sh

RUN scripts/setup_multiple_docker.sh



# Set the default command
CMD ["bash"]
