projects=(
#project_name sdk     reference commit_id
 "aktin"      "$SDK8" 	""  ""
 "dwh-api"    "$SDK8"  	""  ""
 "dwh-db"     "$SDK8" 	""  ""
 "dwh-prefs"  "$SDK8"  	""  ""
 "r-script"   "$SDK8" 	""  ""
 "broker"     "$SDK11" 	""  ""
 "dwh-import" "$SDK8"  	"" ""
 "dwh-query"  "$SDK11"  ""  ""
 "dwh-admin"  "$SDK8"  	"" ""
# "dwh-j2ee"   "$SDK8"  "v1.6rc1"  ""
 "dwh-j2ee"   "$SDK8"  "v1.5.1rc1"  ""
)

INSTANCE="debian"
#INSTANCE="docker"
WILDFLY="dwh1-wildfly-1"